# SVOMO Recommendation App Configuration
# Save this as config.toml in the same directory as your app.py

[app]
name = "SVOMO RECOMMENDATION"
version = "1.1.0"
description = "Your AI-powered movie and anime recommendation system"
author = "SVOMO Team"

[design]
theme = "retro-futuristic"
primary_color = "#00ffcc"
secondary_color = "#ff00aa"
background = "gradient"  # Options: "gradient", "solid", "dark"
animation = true
debug_mode = false

[api]
tmdb_base_url = "https://api.themoviedb.org/3"
gemini_model = "gemini-2.0-flash"
fallback_delay = 500  # milliseconds between API calls if the first one fails

[recommendations]
max_recommendations = 3
search_expansions = true  # Try alternate search terms if initial search fails
include_explanation = true
include_genres = true
include_overview = true

[anime]
special_handling = true
add_anime_keyword = true
try_alternate_titles = true
japanese_titles_fallback = true

[questions]
persona_count = 4
mood_count = 7
step_by_step = true
